version: '3'
services:
   web:
      build: web-rtmp
      ports:
       - "80:80"
       - "443:443"
       - "6503:6503"
       - "1935:1935"
       - "8443:8443"
      volumes:
         - /home/dixieflatline/docker/web-rtmp/html:/usr/share/nginx/html
         - /home/dixieflatline/docker/web-rtmp/nginx.conf:/etc/nginx/nginx.conf
         - ./letsencrypt-site:/usr/share/nginx/html/letsencrypt
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /home/dixieflatline/docker/letsencrypt-volumes/etc/letsencrypt/live/colinwhu.com/fullchain.pem:/etc/letsencrypt/live/colinwhu.com/fullchain.pem
         - /home/dixieflatline/docker/letsencrypt-volumes/etc/letsencrypt/live/colinwhu.com/privkey.pem:/etc/letsencrypt/live/colinwhu.com/privkey.pem
      networks:
         - docker-network

   mumble:
      build: mumble
      ports:
       - "64738:64738"
       - "64738:64738/udp"
      volumes:
         - /home/dixieflatline/docker/mumble/mumble-server:/data

   tempo:
      build: tempo
#      ports:
#       - "3000:3000"
      volumes:
         - /home/dixieflatline/projects/Tempo:/Tempo
      networks:
         - docker-network

networks:
   docker-network:
      driver: bridge
