version: '3'
services:
   web:
      build: web-rtmp
      ports:
       - "80:80"
       - "1935:1935"

   mumble:
      build: mumble
      ports:
       - "64738:64738"
       - "64738:64738/udp"
      volumes:
         - /home/dixieflatline/docker/mumble/mumble-server:/data
