version: '3'
services:
   web:
      build: web-rtmp
      ports:
       - "80:80"
       - "443:443"
       - "1935:1935"
      volumes:
         - /home/dixieflatline/docker/web-rtmp/html:/usr/share/nginx/html
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /home/dixieflatline/docker/letsencrypt-volumes/etc/letsencrypt/live/colinwhu.com/fullchain.pem:/etc/letsencrypt/live/colinwhu.com/fullchain.pem
         - /home/dixieflatline/docker/letsencrypt-volumes/etc/letsencrypt/live/colinwhu.com/privkey.pem:/etc/letsencrypt/live/colinwhu.com/privkey.pem

   mumble:
      build: mumble
      ports:
       - "64738:64738"
       - "64738:64738/udp"
      volumes:
         - /home/dixieflatline/docker/mumble/mumble-server:/data
