FROM tiangolo/nginx-rtmp
#RUN apt-get install build-essential libpcre3 libpcre3-dev libssl-dev
#RUN wget https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/dev.zip
COPY html /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
